#!/bin/sh
#SBATCH -t 12:00:00
#SBATCH --mem=20G
#SBATCH --mail-type=END
#SBATCH --mail-user=tong_shen1@brown.edu
#SBATCH --account=brubenst-condo
#SBATCH --array=1-10
#SBATCH -J CanEnsAFQMC
#SBATCH -e arrayjob_%a.err
#SBATCH -o arrayjob_%a.out

ulimit -s unlimited

time julia --project=@. job.jl

